### PR TITLE
Fixes #387: mock util to fix unit test failure

### LINKED ISSUE #387: Test failure: SidebarLink
**Describe the bug**

**To Reproduce**

```
~/code/ef/ethereum-org-website « git:(dev)
$ yarn test
yarn run v1.19.1
$ jest
 PASS  docs/.vuepress/theme/components/__tests__/Footer.spec.js
 PASS  docs/.vuepress/theme/components/__tests__/NavLink.spec.js
 PASS  docs/.vuepress/components/__tests__/HomePage.spec.js
 PASS  docs/.vuepress/theme/components/__tests__/DropdownLink.spec.js
 PASS  docs/.vuepress/theme/components/__tests__/Hero.spec.js
 PASS  docs/.vuepress/theme/components/__tests__/SearchBox.spec.js
 FAIL  docs/.vuepress/theme/components/__tests__/SidebarLink.spec.js
  ● Console

    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: (0 , _util.resolveHeaderTitle) is not a function"

      (found in <Root>)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:1884
      TypeError: (0 , _util.resolveHeaderTitle) is not a function
          at renderLink (/Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/theme/components/SidebarLink.vue:1080:37)
          at render (/Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/theme/components/SidebarLink.vue:997:31)
          at createFunctionalComponent (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3052:30)
          at createComponent (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3225:12)
          at _createElement (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3421:13)
          at createElement (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3347:10)
          at vm.$createElement (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3481:54)
          at Proxy.parentComponentOptions.render (/Users/samrichards/code/ef/ethereum-org-website/node_modules/@vue/test-utils/dist/vue-test-utils.js:4467:12)
          at VueComponent.Vue._render (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:3532:22)
          at VueComponent.updateComponent (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:4048:21)
          at Watcher.get (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:4459:25)
          at new Watcher (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:4448:12)
          at mountComponent (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:4055:3)
          at VueComponent.Object.<anonymous>.Vue.$mount (/Users/samrichards/code/ef/ethereum-org-website/node_modules/vue/dist/vue.runtime.common.dev.js:8386:10)
          at mount (/Users/samrichards/code/ef/ethereum-org-website/node_modules/@vue/test-utils/dist/vue-test-utils.js:8649:21)
          at shallowMount (/Users/samrichards/code/ef/ethereum-org-website/node_modules/@vue/test-utils/dist/vue-test-utils.js:8677:10)
          at Object.test (/Users/samrichards/code/ef/ethereum-org-website/docs/.vuepress/theme/components/__tests__/SidebarLink.spec.js:47:21)
          at Object.asyncJestTest (/Users/samrichards/code/ef/ethereum-org-website/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
          at resolve (/Users/samrichards/code/ef/ethereum-org-website/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
          at new Promise (<anonymous>)
          at mapper (/Users/samrichards/code/ef/ethereum-org-website/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
          at promise.then (/Users/samrichards/code/ef/ethereum-org-website/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/vue/dist/vue.runtime.common.dev.js:621
      [Vue warn]: Error in render: "TypeError: (0 , _util.resolveHeaderTitle) is not a function"
```

**Expected behavior**
Tests should pass

### PR DESCRIPTION
**Pull request by think-in-universe**
## Description

Fixes #387 

One util function `resolveHeaderTitle` introduced in #369 should be mocked in SidebarLink's unit test.

## Related Issue

#387

## Checklist:

- [x] I have read the contributing guidelines in the project README.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by samajammin** [comment]
Thanks, @think-in-universe! This should have been obvious 😅 🤦‍♂ 

I notice when I now run `yarn test`, I'm hitting some testMatch error:

```
~/code/ef/ethereum-org-website « git:(pr/390)
$ yarn test
yarn run v1.19.1
$ jest
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/samrichards/code/ef/ethereum-org-website
  10 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 10 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Do you not have this issue?

**Comment by think-in-universe** [comment]
@samajammin no. I didn't met this error.

Have you changed anything (such as environment) before this error happens? I assume you could run successfully yesterday.
